//
// This file is generated by "lib/generate-paths.js"
//
var E2D3_DEFAULT_PATHS = {
  'jquery': [
    '//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min',
    'jquery'
  ],
  'async': [
    '//cdnjs.cloudflare.com/ajax/libs/requirejs-plugins/1.0.3/async.min',
    'async'
  ],
  'c3': [
    '//cdnjs.cloudflare.com/ajax/libs/c3/0.4.10/c3.min',
    'c3'
  ],
  'coffee-script': [
    '//cdnjs.cloudflare.com/ajax/libs/coffee-script/1.7.1/coffee-script.min',
    'coffee-script'
  ],
  'crossfilter': [
    '//cdnjs.cloudflare.com/ajax/libs/crossfilter/1.3.12/crossfilter.min',
    'crossfilter'
  ],
  'd3': [
    '//cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min',
    'd3'
  ],
  'd3_4': [
    '//cdnjs.cloudflare.com/ajax/libs/d3/4.13.0/d3.min',
    'd3_4'
  ],
  'd3_5': [
    '//cdnjs.cloudflare.com/ajax/libs/d3/5.16.0/d3.min',
    'd3_5'
  ],
  'd3plus': [
    '//cdnjs.cloudflare.com/ajax/libs/d3plus/1.8.0/d3plus.min',
    'd3plus'
  ],
  'dc': [
    '//cdnjs.cloudflare.com/ajax/libs/dc/1.7.4/dc.min',
    'dc'
  ],
  'mathjs': [
    '//cdnjs.cloudflare.com/ajax/libs/mathjs/2.4.0/math.min',
    'math'
  ],
  'numeric': [
    '//cdnjs.cloudflare.com/ajax/libs/numeric/1.2.6/numeric.min',
    'numeric'
  ],
  'react': [
    '//cdnjs.cloudflare.com/ajax/libs/react/0.14.0/react.min',
    'react'
  ],
  'three': [
    '//cdnjs.cloudflare.com/ajax/libs/three.js/r73/three.min',
    'three'
  ],
  'topojson': [
    '//cdnjs.cloudflare.com/ajax/libs/topojson/1.6.19/topojson.min',
    'topojson'
  ],
  'vue': [
    '//cdnjs.cloudflare.com/ajax/libs/vue/0.12.16/vue.min',
    'vue'
  ],
  'jquery-with-global': [
    '//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min',
    'jquery'
  ],
  'JSXTransformer': [
    '//cdnjs.cloudflare.com/ajax/libs/react/0.13.3/JSXTransformer',
    'JSXTransformer'
  ],
  'font': [
    '//cdnjs.cloudflare.com/ajax/libs/requirejs-plugins/1.0.3/font.min',
    'font'
  ],
  'goog': [
    '//cdnjs.cloudflare.com/ajax/libs/requirejs-plugins/1.0.3/goog.min',
    'goog'
  ],
  'image': [
    '//cdnjs.cloudflare.com/ajax/libs/requirejs-plugins/1.0.3/image.min',
    'image'
  ]
};
var E2D3_DEFAULT_SHIM = {
  'three': {
    'exports': 'THREE'
  },
  'crossfilter': {
    'exports': 'crossfilter'
  },
  'numeric': {
    'exports': 'numeric'
  },
  'bootstrap': {
    'deps': [
      'jquery'
    ]
  }
};
var E2D3_DEFAULT_MAP = {
  '*': {
    'jquery': 'misc/jquery-private',
    'd3': 'misc/d3-promised',
  },
  'misc/jquery-private': {
    'jquery': 'jquery'
  },
  'misc/d3-promised': {
    'd3': 'd3'
  },
  'd3.promise': {
    'd3': 'd3'
  },
  'bootstrap': {
    'jquery': 'jquery'
  }
};
