#
# This file is generated by "lib/generate-paths.js"
#
e2d3_default_paths =
  'c3': ['//cdnjs.cloudflare.com/ajax/libs/c3/0.4.10/c3.min', 'c3']
  'coffee-script': ['//cdnjs.cloudflare.com/ajax/libs/coffee-script/1.9.3/coffee-script.min', 'coffee-script']
  'd3': ['//cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min', 'd3']
  'd3plus': ['//cdnjs.cloudflare.com/ajax/libs/d3plus/1.7.4/d3plus.min', 'd3plus']
  'jquery': ['//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min', 'jquery']
  'react': ['//cdnjs.cloudflare.com/ajax/libs/react/0.13.3/react.min', 'react']
  'topojson': ['//cdnjs.cloudflare.com/ajax/libs/topojson/1.6.19/topojson.min', 'topojson']
  'vue': ['//cdnjs.cloudflare.com/ajax/libs/vue/0.12.1/vue.min', 'vue']
  'JSXTransformer': ['//cdnjs.cloudflare.com/ajax/libs/react/0.13.3/JSXTransformer', 'JSXTransformer']
